### ISSUE TITLE
Plugin not getting updates automatically

### ISSUE THREAD

**Issue by jgudanepti** [modfin/mfn-wp-plugin#34]
Environment: MFN Feed v0.0.58, WP 5.9.1, PHP 7.4.28. 
Feed is not updated until the "Sync Latest" or "Sync All" buttons are pressed.
Is this normal behavior or something is not set correctly?
Can sync be set to work with WP_cron?

**Comment by crholm** [comment]
In general it is intended to work with websub / posthooks to keep the feed up to date instead of wp_cron. This since wp_cron job in general is executed on a visitors php thread slowing down page loads.

Adding credentials provided by modular finance and pressing the subscription button should ensure that the feed is keept up to date. 

@joeledstrom @abulerforrest  
Anything to add here?

**Comment by abulerforrest** [comment]
@crholm @jgudanepti To add, as mentioned in order for the feed to be kept up to date a subscription has to be be established (By clicking the Subscribe button). If a subscription is established you should see the Subscription Id and Posthook name in the Status section in the top right corner. If you are not able to subscribe there may be something wrong in the settings and you are welcome to send us a screenshot to integration@modularfinance.se and we can help to look into it.
